language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --dev --no-interaction
  - phpenv rehash

script:
  - ./vendor/bin/phpcs --standard=./phpcs.xml ./src
  - ./vendor/bin/phpmd ./src text ./phpmd.xml
  - ./vendor/bin/phpdcd ./src
  - ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-text
